version: "3.7"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app
    command: sh -c "yarn install && yarn dev" #volumesを./appにしているのでそのままyarn install
    ports:
      - "9000:3000"
