---
root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
  - prettier
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - prettier
  - plugin:tailwindcss/recommended
ignorePatterns:
  - "*.config.js"
rules:
  prettier/prettier: error
